pull_request_rules:
  - name: Backport to humble branch
    conditions:
      - base=ros2
      - label=backport-humble
    actions:
      backport:
        branches:
          - humble
        labels:
          - humble

  - name: Backport to iron branch
    conditions:
      - base=ros2
      - label=backport-iron
    actions:
      backport:
        branches:
          - iron
        labels:
          - iron
